### ISSUE TITLE
Question about WarMUX history

### ISSUE THREAD

**Issue by Wuzzy2** [yeKcim/warmux#2]
Hi, I know you were involved in the development of WarMUX (graphics). Do you know what happened to the old website? I remember that years ago, one day it just was replaced by something Russian, and later the website was gone completely.
Do you still have contact with other developers and contributors?

I have been wondering for years now why traces of WarMUX have disappeared so apruptly, maybe you know something about the history of the "final days" of WarMUX.

Just curious.

(By the way, back in the day, I contributed something to WarMUX as well, namely I worked on the German translation a bit.)

**Comment by yeKcim** [comment]
I’m not in contact with warmux devs anymore.
At the end, no more devs were involved. Nobody cares about a website about an old game so it was probably hacked.

**Comment by Wuzzy2** [comment]
Heh. I see. Thanks for replying, though.
