### ISSUE TITLE
Website archive

### ISSUE THREAD

**Issue by lynxlynxlynx** [yeKcim/warmux#4]
Hey yekCim, nice job archiving everything! I remembered the project we all worked on, found this place then dug up the website (before the domain expired and got hijacked). It's still visible through the Wayback machine:
http://web.archive.org/web/20120304160644/http://www.wormux.org/phpboost/news/news.php

Maybe worth linking in the readme. 🤷🏾

**Comment by yeKcim** [comment]
Good idea, thanks!
